# Generated by Django 3.1.7 on 2021-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Avatar',
            field=models.CharField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/image-4bfb0.appspot.com/o/Avatar%2Fdefault.png?alt=media', max_length=500, null=True),
        ),
    ]
