# Generated by Django 3.1.7 on 2021-03-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210317_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Avatar',
            field=models.CharField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/image-4bfb0.appspot.com/o/Avatar%2Fdefault.png?alt=media', max_length=1000, null=True),
        ),
    ]
