# Generated by Django 3.1.7 on 2021-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210317_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Avatar',
            field=models.CharField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/image-4bfb0.appspot.com/o/Avatar%2Fdefault.png?alt=media&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjRlMDBlOGZlNWYyYzg4Y2YwYzcwNDRmMzA3ZjdlNzM5Nzg4ZTRmMWUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vaW1hZ2UtNGJmYjAiLCJhdWQiOiJpbWFnZS00YmZiMCIsImF1dGhfdGltZSI6MTYxNjA0Mjk4MiwidXNlcl9pZCI6IlFlTmpBdEpacW1iWUJZc0ZOUWNkUkUxWU01SjMiLCJzdWIiOiJRZU5qQXRKWnFtYllCWXNGTlFjZFJFMVlNNUozIiwiaWF0IjoxNjE2MDQyOTgyLCJleHAiOjE2MTYwNDY1ODIsImVtYWlsIjoiYTAwLm4wcmVwbHlAaG90bWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYTAwLm4wcmVwbHlAaG90bWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Fize_cOO9r25rni_CbxsLEkwwRhC6Ouoj4gtLhHzMNbG4uVFUFVret0YPTVaCng9KuAr679RHsd2itAbEzVotrFik2MuGPQbaGHSOk3MBTU0hLsvotvy_oFt1-GmREuAp2EWtuAR8cHzaNlcOBpam9SBnBgd3sQvTc-g_mISSazm_z-I4430WZyRgj1-T-uXWghVp1M_SV-MQQ1Se6uIjesKe2Cax2I3KFjrsMbERW9W3gvSGor9ZLQL8-cTnFqqyQ0u3Vmbem1V-eGECcq9CSAaNRK8xhZIPgWs6WiQhvjFfUBhJx4edLti6sVy9Gkhrp90xiIc9qB1gmvvdu1JyA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='imagestudent',
            name='Url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='Url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
