# Generated by Django 3.1.7 on 2021-03-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210318_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Avatar',
            field=models.TextField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/image-4bfb0.appspot.com/o/Avatar%2Fdefault.png?alt=media&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjRlMDBlOGZlNWYyYzg4Y2YwYzcwNDRmMzA3ZjdlNzM5Nzg4ZTRmMWUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vaW1hZ2UtNGJmYjAiLCJhdWQiOiJpbWFnZS00YmZiMCIsImF1dGhfdGltZSI6MTYxNjA0MzA3MCwidXNlcl9pZCI6IlFlTmpBdEpacW1iWUJZc0ZOUWNkUkUxWU01SjMiLCJzdWIiOiJRZU5qQXRKWnFtYllCWXNGTlFjZFJFMVlNNUozIiwiaWF0IjoxNjE2MDQzMDcwLCJleHAiOjE2MTYwNDY2NzAsImVtYWlsIjoiYTAwLm4wcmVwbHlAaG90bWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYTAwLm4wcmVwbHlAaG90bWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Nc6tomWMH18c4Ew9gfnEdzbeW8XAyJPXVWUYb7OS8z_Ci1SrgAPHianWH7vRqTRJuvY_gRitgpmqDgkAZ_9Lsn0upe3Pzd2znndF95XnBgk8EaD6nwq4qW2LwnVzrLNtNWX17EEKF7ZCAU2eaZQ0a5gnUZIzG8OAThMbA0zmr5Gv9UxecMLrYyVQbqGBmMHfqWaxL_GFKS7qzK3vECiFsGQ2j9Za9bJoCoFqVA3sKrcxBzCkB_aJspGLj4SAAj-4F1ASlc9vx6hmnwxCHuRWqXWZPajIEVVyNmtPGw3BQh5fGM7y28H3xPI7Np0l5J6Qd14QAfmn6bRwWuhy_l0Xvw', null=True),
        ),
        migrations.AlterField(
            model_name='submenus',
            name='Url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
